names = [
        "admire groove",
         "admire vega",
         "agnes digital",
         "agnes tachyon",
         "air groove",
         "almond eye",
         "aston machan",
         "bamboo memory",
         "biko pegasus",
         "biwa hayahide",
         "bubble gum fellow",
         "buena vista",
         "calstone light o",
         "cesario",
         "cheval grand",
         "copano rickey",
         "curren bouquetdor",
         "curren chan",
         "daiichi ruby",
         "daitaku helios",
         "daiwa scarlet",
         "dantsu flame",
         "dream journey",
         "duramente",
         "durandal",
         "eishin flash",
         "el condor pasa",
         "espoir city",
         "fenomeno",
         "fine motion",
         "forever young",
         "fuji kiseki",
         "fusaichi pandora",
         "gentildonna",
         "gold city",
         "gold ship",
         "grass wonder",
         "haru urara",
         "hishi akebono",
         "hishi amazon",
         "hishi miracle",
         "hokko tarumae",
         "ikuno dictus",
         "inari one",
         "ines fujin",
         "jungle pocket",
         "ks miracle",
         "katsuragi ace",
         "kawakami princess",
         "king halo",
         "kiseki",
         "kitasan black",
         "loves only you",
         "lucky lilac",
         "manhattan cafe",
         "marche lorraine",
         "maruzensky",
         "marvelous sunday",
         "matikanefukukitaru",
         "matikanetannhauser",
         "mayano top gun",
         "meisho doto",
         "mejiro ardan",
         "mejiro bright",
         "mejiro dober",
         "mejiro mcqueen",
         "mejiro palmer",
         "mejiro ramonu",
         "mejiro ryan",
         "mihono bourbon",
         "mr cb",
         "nakayama festa",
         "narita brian",
         "narita taishin",
         "narita top road",
         "neo universe",
         "nice nature",
         "nishino flower",
         "no reason",
         "north flight",
         "oguri cap",
         "orfevre",
         "red desire",
         "rhein kraft",
         "rice shower",
         "royce and royce",
         "rulership",
         "sakura bakushin o",
         "sakura chiyono o",
         "sakura laurel",
         "samson big",
         "satono crown",
         "satono diamond",
         "seeking the pearl",
         "seiun sky",
         "shinko windy",
         "silence suzuka",
         "sirius symboli",
         "smart falcon",
         "sounds of earth",
         "special week",
         "stay gold",
         "still in love",
         "super creek",
         "sweep tosho",
         "symboli kris s",
         "symboli rudolf",
         "tm opera o",
         "taiki shuttle",
         "tamamo cross",
         "tanino gimlet",
         "tap dance city",
         "tokai teio",
         "tosen jordan",
         "transcend",
         "tsurumaru tsuyoshi",
         "twin turbo",
         "verxina",
         "vivlos",
         "vodka",
         "winning ticket",
         "wonder acute",
         "yaeno muteki",
         "yamanin zephyr",
         "yukino bijin",
         "zenno rob roy",]